# GITHUB ACTIONS

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: GitHub Action example
        run: echo "Hello world!"
      - name: Get Date
        run: date
      - name: Show the current directory
        run: ls -la
